global using Azure.Messaging.EventGrid;
global using FluentAssertions;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Moosesoft.SendGrid.Azure.EventGrid;
global using Newtonsoft.Json.Linq;
global using NSubstitute;
global using System.Diagnostics.CodeAnalysis;
global using System.Reflection;
global using System.Text;